server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /dfmanager

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: dm.jdbc.driver.DmDriver
      url: jdbc:dm://app01:5236?schema=DFMANAGER&compatibleMode=mysql&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: DFMANAGER
      password: DFMANAGER
  redis:
    host: 192.168.100.142
    port: 6379
    password: dfManager142

mybatis-plus:
  # 驼峰转换 从数据库列名到Java属性驼峰命名的类似映射
  map-underscore-to-camel-case: true
  # 是否开启缓存
  cache-enable: false
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:com/bj/dfmanager/mapper/xml/*.xml
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

task:
  fixedDelay: 300000

hybase:
  url: http://192.168.100.131:5555
  username: admin
  password: trsadmin
  tasklogtable: F_TASK_LOG
  tables:
    #中国公民证件签发
    - tableName: F_PER_CERT_CHN_ISSUE
      tableComment: 中国公民证件签发
      etlDate: ETLdate
      businessDate: ISSUING_DATE
    #外国人签证签发
    - tableName: F_PER_CERT_FGN_VISA
      tableComment: 外国人签证签发
      etlDate: ETLdate
      businessDate: VISA_DATE
    #外籍人员常住登记
    - tableName: F_PER_FGN_RESIDENT_REG
      tableComment: 外籍人员常住登记
      etlDate: ETLdate
      businessDate: PRMT_ISSUING_DATE
    #外国人临住
    - tableName: F_PER_FGN_TEMP_REG
      tableComment: 外国人临住
      etlDate: ETLdate
      businessDate: STAY_DATE
    #违法违规数据
    - tableName: F_EVT_PSR_ILLEGAL
      tableComment: 违法违规数据
      etlDate: ETLdate
      businessDate: EDIT_DT
    #涉外案事件
    - tableName: F_EVT_FGN_CASE
      tableComment: 涉外案事件
      etlDate: ETLdate
      businessDate: OPER_DT
    #iAPI数据
    - tableName: F_PER_IAPI_INFO
      tableComment: iAPI数据
      etlDate: LOAD_DT
      businessDate: CREATETIME
    #人员基本信息
    - tableName: F_PER_BASIC_INFO
      tableComment: 人员基本信息
      etlDate: ETLdate
      businessDate: ETLdate
    #出入境记录
    - tableName: F_PER_ACT_PSR_IMM_PD
      tableComment: 出入境记录
      etlDate: ETLdate
      businessDate: IMM_DATE
    #三类(港澳台)证件签发
    - tableName: F_PER_CERT_HMT_ISSUE
      tableComment: 三类(港澳台)证件签发
      etlDate: ETLdate
      businessDate: ISSUING_DATE
    #遣返遣送
    - tableName: F_EVT_PSR_REPAT
      tableComment: 遣返遣送
      etlDate: ETLdate
      businessDate: EDIT_DT

dfservice:
  prefix: http://192.168.100.143:9000
  #刷新缓存接口
  reflustCatch: http://192.168.100.142:8080/catch/reflustCatch
  #指标测试接口
  targetTest: http://192.168.100.142:8080/target/test
  #探活接口
  exploreUrl: http://192.168.100.142:8080/status/ping

dfdispatcher:
  #探活接口
  exploreUrl: http://192.168.100.142:8090/status/ping

dftasklogservice:
  #探活接口
  exploreUrl: http://192.168.100.142:8091/status/ping

dfmodelservice:
  #探活接口
  exploreUrl: http://192.168.100.142:8092/status/ping

mq:
  host: 10.6.126.138
  port: 5672
  username: test
  password: test
  timeout: 5000

kafka:
  server: 192.168.100.142:9092
  timeout: 5000

#142新
dfqueryservice:
  ip: 192.168.100.142
  port: 8181

#141
dfmanager141:
  ip: 192.168.100.141
  port: 5236
dataqueryservice141:
  ip: 192.168.100.141
  port: 8090
dfqueryservice141:
  ip: 192.168.100.141
  port: 8181

#143新
dftasklogservice143:
  exploreUrl: http://192.168.100.143:8091/status/ping
dfdispatcher143:
  exploreUrl: http://192.168.100.143:8090/status/ping
dfmodelservice143:
  exploreUrl: http://192.168.100.143:8092/status/ping
dfservice143:
  exploreUrl: http://192.168.100.143:8080/status/ping