-- 1 菜单表
CREATE TABLE "DFMANAGER"."T_MENU"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"PID" INT,
"NAME" VARCHAR(255),
"URL" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_MENU" IS '菜单表';
COMMENT ON COLUMN "DFMANAGER"."T_MENU"."ID" IS '菜单ID';
COMMENT ON COLUMN "DFMANAGER"."T_MENU"."PID" IS '上级菜单ID';
COMMENT ON COLUMN "DFMANAGER"."T_MENU"."NAME" IS '菜单名称';
COMMENT ON COLUMN "DFMANAGER"."T_MENU"."URL" IS '访问路径';


-- 2 模型表
CREATE TABLE "DFMANAGER"."T_MODEL"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"MODEL_NAME" VARCHAR(255),
"MODEL_DESC" VARCHAR(255),
"APPLICATION_SCENARIOS" VARCHAR(500),
"EFFECTIVE_DATE" VARCHAR(50),
"WARN_CONDITION" VARCHAR(255),
"IN_CONDITION_STATUS" VARCHAR(10),
"IN_CONDITION" VARCHAR(255),
"EX_CONDITION_STATUS" VARCHAR(10),
"EX_CONDITION" VARCHAR(255),
"MODEL_STATUS" VARCHAR(10),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_MODEL" IS '模型表';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."ID" IS '主键';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."MODEL_NAME" IS '模型名称';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."MODEL_DESC" IS '模型描述';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."APPLICATION_SCENARIOS" IS '应用场景';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."EFFECTIVE_DATE" IS '有效期';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."WARN_CONDITION" IS '预警规则';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."IN_CONDITION_STATUS" IS '进入条件状态';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."IN_CONDITION" IS '进入条件';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."EX_CONDITION_STATUS" IS '排他规则状态';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."EX_CONDITION" IS '排他规则';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."MODEL_STATUS" IS '模型状态';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL"."UPDATE_TIME" IS '修改时间';


-- 3 模型需求表
CREATE TABLE "DFMANAGER"."T_MODEL_DEMAND"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"MODEL_NAME" VARCHAR(255),
"MODEL_TYPE" VARCHAR(50),
"MODEL_DEMAND" VARCHAR(255),
"USE_SCOPE" VARCHAR(10),
"DEMAND_UNIT" VARCHAR(50),
"DEVELOPER" VARCHAR(50),
"DEMAND_STATUS" VARCHAR(10),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_MODEL_DEMAND" IS '模型需求表';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."MODEL_NAME" IS '模型名称';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."MODEL_TYPE" IS '模型类型';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."MODEL_DEMAND" IS '模型需求';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."USE_SCOPE" IS '使用范围';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."DEMAND_UNIT" IS '需求单位';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."DEVELOPER" IS '开发人员';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."DEMAND_STATUS" IS '需求状态';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_DEMAND"."UPDATE_TIME" IS '修改时间';


-- 4 模型指标表
CREATE TABLE "DFMANAGER"."T_MODEL_TARGET"
(
"MODEL_ID" INT,
"TARGET_ID" INT,
"CODE" VARCHAR(255),
"OPERATOR" VARCHAR(255),
"VALUE_RANGE" VARCHAR(100)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_MODEL_TARGET" IS '模型指标表';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_TARGET"."MODEL_ID" IS '模型ID';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_TARGET"."TARGET_ID" IS '指标ID';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_TARGET"."CODE" IS '编码';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_TARGET"."OPERATOR" IS '运算符';
COMMENT ON COLUMN "DFMANAGER"."T_MODEL_TARGET"."VALUE_RANGE" IS '值域';


-- 5 角色表
CREATE TABLE "DFMANAGER"."T_ROLE"
(
"ROLE_ID" INT IDENTITY(1, 1) NOT NULL,
"ROLE_NAME" VARCHAR(255),
"ROLE_DESC" VARCHAR(255),
"ROLE_STATUS" VARCHAR(10),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_ROLE" IS '角色表';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE"."ROLE_DESC" IS '角色描述';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE"."ROLE_STATUS" IS '角色状态';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE"."UPDATE_TIME" IS '修改时间';


-- 6 角色菜单表
CREATE TABLE "DFMANAGER"."T_ROLE_MENU"
(
"ROLE_ID" INT,
"MENU_ID" INT) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_ROLE_MENU" IS '角色菜单表';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE_MENU"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "DFMANAGER"."T_ROLE_MENU"."MENU_ID" IS '菜单ID';


-- 7 指标表
CREATE TABLE "DFMANAGER"."T_TARGET"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"TARGET_CODE" VARCHAR(255),
"TARGET_NAME" VARCHAR(255),
"CALL_METHOD" VARCHAR(255),
"ASYNC" VARCHAR(10),
"TARGET_PARAM" LONGVARCHAR,
"RETURN_STRUCTURE" LONGVARCHAR,
"RETURN_MODEL" LONGVARCHAR,
"TARGET_LOGIC" LONGVARCHAR,
"TARGET_DESC" VARCHAR(255),
"APPLICABLE_SCOPE" VARCHAR(255),
"TARGET_STATUS" VARCHAR(1),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_TARGET" IS '指标表';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."TARGET_CODE" IS '指标编码';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."TARGET_NAME" IS '指标名称';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."CALL_METHOD" IS '请求方式';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."ASYNC" IS 'N-同步/Y-异步';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."TARGET_PARAM" IS '指标参数';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."RETURN_STRUCTURE" IS '返回数据结构';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."RETURN_MODEL" IS '返回数据模式';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."TARGET_LOGIC" IS '指标逻辑（代码内容）';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."TARGET_DESC" IS '指标描述';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."APPLICABLE_SCOPE" IS '适用范围（编码）';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."TARGET_STATUS" IS '指标状态';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET"."UPDATE_TIME" IS '修改时间';


-- 8 用户表
CREATE TABLE "DFMANAGER"."T_USER"
(
"USER_ID" INT IDENTITY(1, 1) NOT NULL,
"USER_NAME" VARCHAR(255),
"PASSWORD" VARCHAR(255),
"TOKEN" VARCHAR(255),
"REAL_NAME" VARCHAR(255),
"POLICE_NO" VARCHAR(255),
"ID_CARD" VARCHAR(255),
"GENDER" VARCHAR(10),
"USER_STATUS" VARCHAR(10),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("USER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_USER" IS '用户表';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."USER_NAME" IS '用户名/登录名';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."PASSWORD" IS '登录密码';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."TOKEN" IS 'token';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."REAL_NAME" IS '真实姓名';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."POLICE_NO" IS '警号';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."ID_CARD" IS '身份证号';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."GENDER" IS '性别';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."USER_STATUS" IS '用户状态';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_USER"."UPDATE_TIME" IS '修改时间';


-- 9 用户角色表
CREATE TABLE "DFMANAGER"."T_USER_ROLE"
(
"USER_ID" INT,
"ROLE_ID" INT) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_USER_ROLE" IS '用户角色表';
COMMENT ON COLUMN "DFMANAGER"."T_USER_ROLE"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "DFMANAGER"."T_USER_ROLE"."ROLE_ID" IS '角色ID';


-- 10 服务目录菜单表
CREATE TABLE "DFMANAGER"."T_SERVICE_MENU"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"PID" INT,
"NAME" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_SERVICE_MENU" IS '服务目录菜单表';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_MENU"."ID" IS '菜单ID';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_MENU"."PID" IS '上级菜单ID';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_MENU"."NAME" IS '菜单名称';


-- 11 服务目录表
CREATE TABLE "DFMANAGER"."T_SERVICE_INFO"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"SERVICE_MENU_ID" INT,
"SERVICE_CODE" VARCHAR(255),
"SERVICE_NAME" VARCHAR(255),
"SERVICE_URL" VARCHAR(255),
"SERVICE_DESC" VARCHAR(255),
"SERVICE_API" VARCHAR(255),
"SERVICE_STATUS" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_SERVICE_INFO" IS '服务目录表';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_MENU_ID" IS '服务目录ID';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_CODE" IS '服务编码';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_NAME" IS '服务名称';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_URL" IS '服务URL';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_DESC" IS '服务描述';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_API" IS '服务API';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."SERVICE_STATUS" IS '服务状态';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_SERVICE_INFO"."UPDATE_TIME" IS '修改时间';


-- 12 指标校验规则表
CREATE TABLE "DFMANAGER"."T_TARGET_CHECK_RULE"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"RULE_CODE" VARCHAR(255),
"RULE_NAME" VARCHAR(255),
"PARAM_TYPE" VARCHAR(255),
"IS_NULL" VARCHAR(10),
"PARAM_FORMAT" VARCHAR(255),
"PARAM_RANGE_START" VARCHAR(255),
"PARAM_RANGE_END" VARCHAR(255),
"PARAM_ENUM" VARCHAR(255),
"EXPRESSION_RULE" VARCHAR(255),
"RULE_DESC" VARCHAR(255),
"RULE_STATUS" VARCHAR(10),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_TARGET_CHECK_RULE" IS '指标校验规则表';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."ID" IS 'ID';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."RULE_CODE" IS '规则编码';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."RULE_NAME" IS '规则名称';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."PARAM_TYPE" IS '参数类型';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."IS_NULL" IS '是否必填';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."PARAM_FORMAT" IS '参数格式';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."PARAM_RANGE_START" IS '参数范围-起';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."PARAM_RANGE_END" IS '参数范围-止';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."PARAM_ENUM" IS '参数枚举';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."EXPRESSION_RULE" IS '指标逻辑表达式的校验规则';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."RULE_DESC" IS '规则描述';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."RULE_STATUS" IS '规则状态';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_TARGET_CHECK_RULE"."UPDATE_TIME" IS '修改时间';


-- 13 数据API表
CREATE TABLE "DFMANAGER"."T_DATA_API"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"RES_OBJ_CODE" VARCHAR(255),
"RES_OBJ_NAME" VARCHAR(255),
"RES_OBJ_URL" VARCHAR(255),
"RES_OBJ_DESC" VARCHAR(255),
"RES_OBJ_API" LONGVARCHAR,
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_DATA_API" IS '数据API表';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."ID" IS 'ID';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."RES_OBJ_CODE" IS '资源对象编码';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."RES_OBJ_NAME" IS '资源对象名称';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."RES_OBJ_URL" IS '获取方法';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."RES_OBJ_DESC" IS '描述';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."RES_OBJ_API" IS 'API';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_DATA_API"."UPDATE_TIME" IS '修改时间';


-- 14 监控任务表
CREATE TABLE "DFMANAGER"."T_MONITOR_TASK"
(
"TASK_CODE" VARCHAR(50),
"TASK_DESC" VARCHAR(255),
"MONITOR_STATUS" VARCHAR(10),
"TASK_TIME" VARCHAR(255),
"SORT" INT,
"UPDATE_TIME" TIMESTAMP(6)) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_MONITOR_TASK" IS '监控任务表';
COMMENT ON COLUMN "DFMANAGER"."T_MONITOR_TASK"."TASK_CODE" IS '任务编码';
COMMENT ON COLUMN "DFMANAGER"."T_MONITOR_TASK"."TASK_DESC" IS '任务描述';
COMMENT ON COLUMN "DFMANAGER"."T_MONITOR_TASK"."MONITOR_STATUS" IS '任务状态';
COMMENT ON COLUMN "DFMANAGER"."T_MONITOR_TASK"."TASK_TIME" IS '任务用时';
COMMENT ON COLUMN "DFMANAGER"."T_MONITOR_TASK"."SORT" IS '排序';
COMMENT ON COLUMN "DFMANAGER"."T_MONITOR_TASK"."UPDATE_TIME" IS '任务最新执行时间';


-- 15 模板表
CREATE TABLE "DFMANAGER"."T_TEMPLATE"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"TITLE" VARCHAR(255),
"DESCRIPTION" VARCHAR(255),
"CODE" LONGVARCHAR,
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_TEMPLATE" IS '模板表';
COMMENT ON COLUMN "DFMANAGER"."T_TEMPLATE"."ID" IS 'ID';
COMMENT ON COLUMN "DFMANAGER"."T_TEMPLATE"."TITLE" IS '标题';
COMMENT ON COLUMN "DFMANAGER"."T_TEMPLATE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DFMANAGER"."T_TEMPLATE"."CODE" IS '代码';
COMMENT ON COLUMN "DFMANAGER"."T_TEMPLATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_TEMPLATE"."UPDATE_TIME" IS '修改时间';


-- 16 用户系统表
CREATE TABLE "DFMANAGER"."T_USE_SYSTEM_INFO"
(
"ID" INT IDENTITY(1, 1) NOT NULL,
"SYSTEM_NAME" VARCHAR(255),
"CONTACT_USER" VARCHAR(100),
"TEL_INFO" VARCHAR(100),
"LOGIN_NAME" VARCHAR(100),
"LOGIN_PWD" VARCHAR(100),
"AUTH_CODE" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(6),
"UPDATE_TIME" TIMESTAMP(6),
"STATUS" VARCHAR(10),
"SYSTEM_CODE" VARCHAR(100),
"RESULT_QUEUE" VARCHAR(100),
CONSTRAINT "T_USE_SYSTEM_INFO_PK" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "DFMANAGER"."T_USE_SYSTEM_INFO" IS '用户系统信息';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."SYSTEM_NAME" IS '系统名称';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."CONTACT_USER" IS '联系人';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."TEL_INFO" IS '电话';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."LOGIN_NAME" IS '登录名';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."LOGIN_PWD" IS '登录密码';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."AUTH_CODE" IS '授权码';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."STATUS" IS '状态';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."SYSTEM_CODE" IS '系统编码';
COMMENT ON COLUMN "DFMANAGER"."T_USE_SYSTEM_INFO"."RESULT_QUEUE" IS '消息队列';